Repository artefactual/atom, pull requests merged in 2023-10, with the labels that each got.

#1674 WCAG (2.4.2): Add proper page titles. (#1673)
  apps/qubit/modules/clipboard/actions/loadAction.class.php
  apps/qubit/modules/default/actions/browseAction.class.php
  apps/qubit/modules/function/actions/browseAction.class.php
  apps/qubit/modules/menu/actions/listAction.class.php
  apps/qubit/modules/object/actions/importSelectAction.class.php
  apps/qubit/modules/object/actions/validateCsvAction.class.php
  apps/qubit/modules/physicalobject/actions/browseAction.class.php
  apps/qubit/modules/rightsholder/actions/browseAction.class.php
  apps/qubit/modules/search/actions/descriptionUpdatesAction.class.php
  apps/qubit/modules/settings/actions/menuComponent.class.php
  apps/qubit/modules/settings/actions/visibleElementsAction.class.php
  apps/qubit/modules/staticpage/actions/listAction.class.php
  apps/qubit/modules/taxonomy/actions/indexAction.class.php
  apps/qubit/modules/taxonomy/actions/listAction.class.php
  apps/qubit/modules/user/actions/listAction.class.php
  plugins/qbAclPlugin/modules/aclGroup/actions/listAction.class.php
  plugins/qtAccessionPlugin/modules/accession/actions/browseAction.class.php
  plugins/qtAccessionPlugin/modules/donor/actions/browseAction.class.php
  plugins/sfPluginAdminPlugin/modules/sfPluginAdminPlugin/actions/pluginsAction.class.php
  plugins/sfPluginAdminPlugin/modules/sfPluginAdminPlugin/actions/themesAction.class.php
  plugins/sfSkosPlugin/modules/sfSkosPlugin/actions/importAction.class.php
Labels: Type: enhancement

#1660 Fix search query special chars (#1605)
  plugins/arElasticSearchPlugin/lib/arElasticSearchPluginUtil.class.php
Labels: Type: bug

#1657 Fix DO regen task query conditions (#1643)
  lib/task/digitalobject/digitalObjectRegenDerivativesTask.class.php
Labels: Type: bug

#1664 Fix update function for 'Language and script notes'. (#13657)
  lib/model/QubitObject.php
  plugins/sfIsadPlugin/lib/sfIsadPlugin.class.php
  plugins/sfRadPlugin/lib/sfRadPlugin.class.php
Labels: Type: bug

#1629 Add phys. storage creation REST endpoint. (#1628)
  plugins/arRestApiPlugin/config/arRestApiPluginConfiguration.class.php
  plugins/arRestApiPlugin/modules/api/actions/physicalobjectsCreateAction.class.php
Labels: Type: enhancement

#1677 Prevent addition of incomplete access points. (#1661)
  js/autocomplete.js
Labels: Type: bug

#1641 Update cookie security settings
  apps/qubit/config/qubitConfiguration.class.php
  apps/qubit/modules/user/actions/loginAction.class.php
  lib/myUser.class.php
Labels: Type: enhancement

#1681 Provide informative csrf attack message. (#1678)
  vendor/symfony/lib/validator/sfValidatorCSRFToken.class.php
Labels: Type: enhancement

#1679 Fix GA4 tracking for fullwidth treeview. (#1606)
  js/fullWidthTreeView.js
  plugins/arDominionB5Plugin/js/fullWidthTreeView.js
Labels: Type: bug, work-in-progress

#1676 Fix institutional search box options (#1635)
  apps/qubit/modules/informationobject/templates/_advancedSearch.php
  apps/qubit/modules/search/templates/_box.php
  apps/qubit/templates/_header.php
  plugins/arArchivesCanadaPlugin/css/less/header.less
  plugins/arArchivesCanadaPlugin/modules/search/templates/_box.php
  plugins/arArchivesCanadaPlugin/templates/_header.php
  plugins/arDominionB5Plugin/modules/informationobject/templates/_advancedSearch.php
  plugins/arDominionB5Plugin/modules/search/templates/_box.php
Labels: Type: bug
