Repository artefactual/atom, pull requests merged in 2023-07, with the labels that each got.

#1619 Add a CLI rename slug tool (#1609)
  lib/task/tools/renameSlugTask.class.php
Labels: Type: feature

#1617 Add treeview sync code to the BS5 theme (#1616)
  plugins/arDominionB5Plugin/js/fullWidthTreeView.js
Labels: Type: bug

#1631 Fix D.O. create REST endpoint ACL check. (#1630)
  plugins/arRestApiPlugin/modules/api/actions/digitalobjectsCreateAction.class.php
Labels: Type: bug

#1626 Add IO pub. status update via REST API. (#1624)
  plugins/arRestApiPlugin/modules/api/actions/informationobjectsUpdateAction.class.php
Labels: Type: enhancement

#1638 Bump fontawesome version
  package-lock.json
  package.json
Labels: dependencies
