Repository artefactual/atom, pull requests merged in 2023-09, with the labels that each got.

#1649 Add deprecation notice for BS2 theme (#1642)
  apps/qubit/modules/default/actions/bs2DeprecationMessageComponent.class.php
  apps/qubit/modules/default/actions/bs2DeprecationMessageDismissAction.class.php
  apps/qubit/modules/default/templates/_bs2DeprecationMessage.php
  apps/qubit/templates/_header.php
  js/bs2DeprecationMessage.js
  plugins/arArchivesCanadaPlugin/templates/_header.php
  plugins/arDominionPlugin/css/less/scaffolding.less
Labels: Type: enhancement

#1658 Add tab for viewing failed jobs (#1613)
  apps/qubit/modules/jobs/actions/browseAction.class.php
  apps/qubit/modules/jobs/templates/browseSuccess.php
  plugins/arDominionB5Plugin/modules/jobs/templates/browseSuccess.php
Labels: Type: enhancement

#1670 Cypress: Upgrade to v13.2 and update tests.
  .github/workflows/integration-tests.yml
  cypress/e2e/csv_import.cy.js
  cypress/e2e/finding_aid.cy.js
  package-lock.json
  package.json
Labels: dependencies

#1665 Fix npm install for Docker. (#1662)
  Dockerfile
Labels: Type: bug, good first issue

#1669 Add error handling for tools:rename-slug. (#1666)
  lib/task/tools/renameSlugTask.class.php
Labels: Type: bug
