Repository artefactual/atom, pull requests merged in 2024-08, with the labels that each got.

#1853 Fix accordion button icons for BS5 theme
  plugins/arDominionB5Plugin/scss/_layout.scss
  plugins/arDominionB5Plugin/scss/main.scss
Labels: Type: bug

#1851 Update app.yml CSP Directives Structure
  config/app.yml
Labels: Type: enhancement

#1858 Update cypress and fix flaky tests
  cypress.config.js
  package-lock.json
  package.json
  plugins/arDominionB5Plugin/js/searchBox.js
Labels: dependencies

#1859 Bump npm dependencies
  package-lock.json
Labels: dependencies

#1865 Bump webpack version
  package-lock.json
Labels: dependencies
