Repository artefactual/atom, pull requests merged in 2024-05, with the labels that each got.

#1808 Add URL support to D.O. load task (#1807)
  lib/task/digitalobject/digitalObjectLoadTask.class.php
Labels: Type: feature

#1806 Fix translationLinksComponent dropdown (#1805)
  apps/qubit/modules/default/actions/translationLinksComponent.class.php
Labels: Type: bug

#1816 Fix diacritics typo. (#1813)
  apps/qubit/modules/settings/actions/diacriticsAction.class.php
Labels: good first issue

#1780 Fix tooltips for BS5 (#1777)
  cypress/e2e/descriptions.cy.js
  plugins/arDominionB5Plugin/js/tooltip.js
  plugins/arDominionB5Plugin/scss/_forms.scss
  plugins/arDominionB5Plugin/templates/_layout_start_webpack.php
Labels: Type: bug
