Repository artefactual/atom, pull requests merged in 2025-04, with the labels that each got.

#1968 Set the gh workflow to use PHP-FPM 8.3
  .github/workflows/integration-tests.yml
Labels: dependencies

#1939 Bump composer dependencies
  .github/workflows/syntax-checks.yml
  .php-cs-fixer.dist.php
  composer.lock
  test/phpunit/CsvImportAuditerTest.php
  test/phpunit/PhysicalObjectCsvHoldingsReportTest.php
  test/phpunit/PhysicalobjectCsvImporterTest.php
  test/phpunit/arOidcPlugin/config/ArOidcPluginConfigurationTest.php
  test/phpunit/arOidcPlugin/lib/ArOidcTest.php
  test/phpunit/arOidcPlugin/lib/oidcUserTest.php
  test/phpunit/lib/filter/QubitCspFilterTest.php
  test/phpunit/settingsTaskTest.php
  vendor/symfony/lib/plugin/sfPearFrontendPlugin.class.php
Labels: dependencies

#1961 Fix PHP 8.x deprecation warnings (#1960)
  lib/model/QubitDigitalObject.php
  lib/model/QubitNote.php
  lib/model/om/BaseAccessLog.php
  lib/model/om/BaseActor.php
  lib/model/om/BaseAuditLog.php
  lib/model/om/BaseClipboardSave.php
  lib/model/om/BaseClipboardSaveItem.php
  lib/model/om/BaseContactInformationI18n.php
  lib/model/om/BaseDigitalObject.php
  lib/model/om/BaseEvent.php
  lib/model/om/BaseEventI18n.php
  lib/model/om/BaseFunctionObjectI18n.php
  lib/model/om/BaseGrantedRight.php
  lib/model/om/BaseKeymap.php
  lib/model/om/BaseMenu.php
  lib/model/om/BaseMenuI18n.php
  lib/model/om/BaseNoteI18n.php
  lib/model/om/BaseOaiHarvest.php
  lib/model/om/BaseOaiRepository.php
  lib/model/om/BaseOtherNameI18n.php
  lib/model/om/BasePhysicalObject.php
  lib/model/om/BasePhysicalObjectI18n.php
  lib/model/om/BaseProperty.php
  lib/model/om/BasePropertyI18n.php
  lib/model/om/BaseRelation.php
  lib/model/om/BaseRelationI18n.php
  lib/model/om/BaseRightsI18n.php
  lib/model/om/BaseStaticPageI18n.php
  lib/model/om/BaseTerm.php
  lib/model/om/BaseTermI18n.php
  plugins/qbAclPlugin/lib/model/om/BaseAclPermission.php
  plugins/qtAccessionPlugin/lib/model/om/BaseAccessionEventI18n.php
  plugins/qtAccessionPlugin/lib/model/om/BaseAccessionI18n.php
  plugins/qtAccessionPlugin/lib/model/om/BaseDeaccessionI18n.php
  plugins/sfDcPlugin/lib/sfDcPlugin.class.php
  plugins/sfEacPlugin/lib/sfEacPlugin.class.php
  plugins/sfEadPlugin/lib/sfEadPlugin.class.php
  plugins/sfEadPlugin/modules/sfEadPlugin/templates/indexSuccessBody.xml.php
  plugins/sfEadPlugin/modules/sfEadPlugin/templates/indexSuccessBodyDidElement.xml.php
  plugins/sfIsaarPlugin/lib/sfIsaarPlugin.class.php
  plugins/sfIsadPlugin/lib/sfIsadPlugin.class.php
  plugins/sfIsdfPlugin/lib/sfIsdfPlugin.class.php
  plugins/sfModsPlugin/lib/sfModsPlugin.class.php
  vendor/symfony/lib/cache/sfAPCCache.class.php
  vendor/symfony/lib/form/sfFormField.class.php
Labels: php

#1893 Hide hidden ISAD/RAD/DACS elements for public EAD XML. (#1879)
  plugins/sfEadPlugin/modules/sfEadPlugin/actions/indexAction.class.php
  plugins/sfEadPlugin/modules/sfEadPlugin/templates/indexSuccessBody.xml.php
  plugins/sfEadPlugin/modules/sfEadPlugin/templates/indexSuccessBodyBioghistElement.xml.php
  plugins/sfEadPlugin/modules/sfEadPlugin/templates/indexSuccessBodyDidElement.xml.php
Labels: Type: enhancement, work-in-progress

#2004 Allow searching accessions by linked terms
  plugins/arElasticSearchPlugin/config/mapping.yml
  plugins/arElasticSearchPlugin/lib/model/arElasticSearchAccession.class.php
  plugins/qtAccessionPlugin/modules/accession/actions/browseAction.class.php
Labels: Community

#1993 Enable PHP debugging in docker
  Dockerfile
  docker/docker-compose.dev.yml
  docker/etc/php/xdebug.ini
Labels: Community
