Repository artefactual/atom, pull requests merged in 2025-07, with the labels that each got.

#2080 Enable translations for clipboard 'count'. (#2078)
  data/fixtures/settings.yml
  lib/task/migrate/migrations/arMigration0194.class.php
  plugins/arDominionB5Plugin/js/clipboard.js
  plugins/arDominionB5Plugin/modules/menu/templates/_clipboardMenu.php
Labels: Type: enhancement

#2086 Fix CSV exports with hidden elements. (#2041)
  lib/flatfile/QubitFlatfileExport.class.php
Labels: Type: bug

#2096 Exclude accessionNumber from public CSV exports.
  lib/flatfile/QubitFlatfileExport.class.php
Labels: Type: bug

#2102 Enhance accessibility of PDF finding aids
  lib/QubitFindingAidGenerator.class.php
  lib/task/pdf/ead-pdf-common.xsl
  lib/task/pdf/ead-pdf-full-details.xsl
  lib/task/pdf/ead-pdf-inventory-summary.xsl
  lib/task/pdf/helper-functions.xsl
Labels: Community

#2085 Restore new related material formatting and fix 500 error when linking containers
  apps/qubit/modules/informationobject/templates/_relatedMaterialDescriptions.php
  plugins/arDominionB5Plugin/modules/informationobject/templates/_relatedMaterialDescriptions.php
Labels: Community
